version: '3'
services:
    redis:
      image: redis:latest
      environment:
        - TZ=EST

    mysql:
      image: mariadb
      environment:
        MYSQL_ROOT_PASSWORD: example
        MYSQL_USER: undead
        MYSQL_PASSWORD: undead
        MYSQL_DATABASE: SourceUndead
      ports:
        - 3306:3306
      volumes:
        - ./db:/docker-entrypoint-initdb.d
        - db_data:/var/lib/mysql

    sourceundead:
      build: .
      volumes:
        - .:/SourceUndead/
        - /SourceUndead/node_modules/
      environment:
        REDIS_ENV: redis
        MYSQL_HOST: mysql
        MYSQL_USER: undead
        MYSQL_PASSWORD: undead
      restart: unless-stopped
      depends_on:
        - mysql
        - redis
      links:
        - mysql
        - redis
      ports:
        - 8080:8080
        - 3000:3000
      command: >
        sh -c 'npm start'

volumes:
    db_data: